In [4]:

import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.optimizers import RMSprop
from keras.datasets import mnist 
import matplotlib.pyplot as plt
from sklearn import metrics
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder

In [5]:
df=pd.read_csv('/content/letter-recognition.csv')


In [6]:
df

letter  xbox   ybox   width   height  onpix   xbar   ybar   x2bar  \
0          T      2      8       3       5       1      8     13      0   
1          I      5     12       3       7       2     10      5      5   
2          D      4     11       6       8       6     10      6      2   
3          N      7     11       6       6       3      5      9      4   
4          G      2      1       3       1       1      8      6      6   
...      ...    ...    ...     ...     ...     ...    ...    ...    ...   
19995      D      2      2       3       3       2      7      7      7   
19996      C      7     10       8       8       4      4      8      6   
19997      T      6      9       6       7       5      6     11      3   
19998      S      2      3       4       2       1      8      7      2   
19999      A      4      9       6       6       2      9      5      3   

       y2bar   xybar   x2ybar  xy2bar  xedge   xedgey  yedge   yedgex  
0           6       6      10       8       0       8       0       8  
1           4      13       3       9       2       8       4      10  
2           6      10       3       7       3       7       3       9  
3           6       4       4      10       6      10       2       8  
4           6       6       5       9       1       7       5      10  
...       ...     ...     ...     ...     ...     ...     ...     ...  
19995       6       6       6       4       2       8       3       7  
19996       9      12       9      13       2       9       3       7  
19997       7      11       9       5       2      12       2       4  
19998       6      10       6       8       1       9       5       8  
19999       1       8       1       8       2       7       2       8  

[20000 rows x 17 columns]

In [7]:
df.dtypes


letter    object
xbox       int64
ybox       int64
width      int64
height     int64
onpix      int64
xbar       int64
ybar       int64
x2bar      int64
y2bar      int64
xybar      int64
x2ybar     int64
xy2bar     int64
xedge      int64
xedgey     int64
yedge      int64
yedgex     int64
dtype: object

In [9]:
x=df.drop('letter',axis=1).values
y=df['letter'].values


In [10]:
print(x.shape)
print(y.shape)

(20000, 16)
(20000,)


In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.20)

In [12]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(16000, 16)
(16000,)
(4000, 16)
(4000,)


In [13]:
x_train[0]

array([ 4,  7,  5,  5,  4,  6,  7,  3,  7, 11,  8,  9,  3,  8,  4,  8])

In [14]:
y_train[0]

'E'

In [15]:
x_train=x_train/255
x_test=x_test/255

In [16]:
x_train[0]

array([0.01568627, 0.02745098, 0.01960784, 0.01960784, 0.01568627,
       0.02352941, 0.02745098, 0.01176471, 0.02745098, 0.04313725,
       0.03137255, 0.03529412, 0.01176471, 0.03137255, 0.01568627,
       0.03137255])

In [17]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [18]:
model = Sequential()
model.add(Dense(512,activation='relu',input_shape=(16,)))
model.add(Dense(256,activation='relu'))
model.add(Dense(26,activation='softmax'))

In [19]:
model.compile(loss='sparse_categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
batch_size=128
epochs=50

In [20]:
history=model.fit(x_train,y_train,batch_size=batch_size,epochs=epochs,verbose=1,validation_data=(x_test,y_test))

Epoch 1/50
125/125 [==============================] - 2s 10ms/step - loss: 3.1084 - accuracy: 0.1659 - val_loss: 2.7085 - val_accuracy: 0.2858
Epoch 2/50
125/125 [==============================] - 1s 8ms/step - loss: 2.3399 - accuracy: 0.3281 - val_loss: 2.1046 - val_accuracy: 0.3685
Epoch 3/50
125/125 [==============================] - 1s 8ms/step - loss: 1.9696 - accuracy: 0.4238 - val_loss: 1.8320 - val_accuracy: 0.4538
Epoch 4/50
125/125 [==============================] - 1s 7ms/step - loss: 1.7640 - accuracy: 0.4751 - val_loss: 1.6860 - val_accuracy: 0.5070
Epoch 5/50
125/125 [==============================] - 1s 8ms/step - loss: 1.6293 - accuracy: 0.5145 - val_loss: 1.5670 - val_accuracy: 0.5330
Epoch 6/50
125/125 [==============================] - 1s 7ms/step - loss: 1.5305 - accuracy: 0.5459 - val_loss: 1.4749 - val_accuracy: 0.5690
Epoch 7/50
125/125 [==============================] - 1s 8ms/step - loss: 1.4600 - accuracy: 0.5677 - val_loss: 1.4232 - val_accuracy: 0.5925
Epoch

In [21]:
x_test[100]

array([0.02745098, 0.05098039, 0.02745098, 0.03137255, 0.01960784,
       0.03921569, 0.01960784, 0.00784314, 0.01960784, 0.03529412,
       0.01568627, 0.03137255, 0.02352941, 0.03137255, 0.02352941,
       0.03529412])

In [22]:
lab=encoder.inverse_transform([y_test[100]])
print("Actual Label : ",lab[0])

Actual Label :  R


In [23]:
result=model.predict(x_test)

125/125 [==============================] - 0s 2ms/step


In [25]:
print(result[10])

[3.31651754e-05 6.79568172e-01 1.24732219e-06 1.71592906e-01
 4.70924238e-03 4.75593936e-03 1.87231868e-04 4.75132130e-02
 2.14144675e-04 5.13943494e-04 1.80119497e-03 2.95509635e-05
 4.09868553e-05 6.06200365e-06 1.68413826e-04 3.72703740e-04
 4.12838599e-05 8.12079459e-02 4.27900488e-03 1.31948822e-04
 1.99091819e-08 1.06442926e-07 1.46475754e-09 1.35607680e-03
 2.49694239e-08 1.47559436e-03]


In [26]:
final_value=np.argmax(result[10])

In [27]:
print("Actual label ",y_test[10])
print("Predicted label",final_value)

Actual label  1
Predicted label 1


In [28]:
actual=encoder.inverse_transform([y_test[10]])
predicted=encoder.inverse_transform([final_value])

In [29]:

print("Actual label ",actual)
print("Predicted label",predicted)

Actual label  ['B']
Predicted label ['B']
